services:
  api: 
    container_name: express-api
    build: .
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/devdifferent
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    container_name: mongodb
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: