services:
  api: 
    container_name: express-api
    build: .
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
      - SUPABASE_BUCKET_REGION=${SUPABASE_BUCKET_REGION}
      - SUPABASE_BUCKET_ENDPOINT=${SUPABASE_BUCKET_ENDPOINT}
      - SUPABASE_BUCKET_KEY_ID=${SUPABASE_BUCKET_KEY_ID}
      - SUPABASE_BUCKET_SECRET_KEY=${SUPABASE_BUCKET_SECRET_KEY}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    container_name: mongodb
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: